version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout

      # build and push Docker image
      - run: |
          TAG=$CIRCLE_TAG
          docker build -t codehimanshu/get-video-duration:$TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push codehimanshu/get-video-duration:$TAG